#!/bin/bash

# A script that will print out a message from a variable

hello_message='Hello World!'
current_dir=$(pwd)
readonly variable_wont_change="green"
variable_wont_change="red"
echo "$hello_message from $current_dir your favorite color is $variable_wont_change"
